In [1]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv("PS_20174392719_1491204439457_log.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'PS_20174392719_1491204439457_log.csv'

In [5]:
import os
print(os.getcwd())

c:\Users\Hiral\OneDrive\Desktop\AML_Project\notebooks

In [6]:
import os

print(os.listdir())

['data_loading.ipynb']

In [7]:
print(os.listdir("../dataset"))

['PS_20174392719_1491204439457_log.csv']

In [ ]:
import pandas as pd

df = pd.read_csv("../dataset/PS_20174392719_1491204439457_log.csv")

In [9]:

import os

print(os.listdir("../dataset"))

['PS_20174392719_1491204439457_log.csv']

In [10]:
import os

file_path = os.path.abspath("../dataset/PS_20174392719_1491204439457_log.csv")
print(file_path)
print(os.path.exists(file_path))

c:\Users\Hiral\OneDrive\Desktop\AML_Project\dataset\PS_20174392719_1491204439457_log.csv
True

In [14]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Hiral\OneDrive\Desktop\AML_Project\dataset\PS_20174392719_1491204439457_log.csv")

df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0

In [15]:
df.shape

(6362620, 11)

In [16]:
df.columns

Index(['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig',
       'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFraud',
       'isFlaggedFraud'],
      dtype='str')

In [17]:
df.dtypes

step                int64
type                  str
amount            float64
nameOrig              str
oldbalanceOrg     float64
newbalanceOrig    float64
nameDest              str
oldbalanceDest    float64
newbalanceDest    float64
isFraud             int64
isFlaggedFraud      int64
dtype: object

In [18]:
df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [19]:
df.describe()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
count,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06
mean,2.433972e+02,1.798619e+05,8.338831e+05,8.551137e+05,1.100702e+06,1.224996e+06,1.290820e-03,2.514687e-06
std,1.423320e+02,6.038582e+05,2.888243e+06,2.924049e+06,3.399180e+06,3.674129e+06,3.590480e-02,1.585775e-03
min,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.560000e+02,1.338957e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2.390000e+02,7.487194e+04,1.420800e+04,0.000000e+00,1.327057e+05,2.146614e+05,0.000000e+00,0.000000e+00
75%,3.350000e+02,2.087215e+05,1.073152e+05,1.442584e+05,9.430367e+05,1.111909e+06,0.000000e+00,0.000000e+00
max,7.430000e+02,9.244552e+07,5.958504e+07,4.958504e+07,3.560159e+08,3.561793e+08,1.000000e+00,1.000000e+00

In [20]:
df["isFraud"].value_counts()

isFraud
0    6354407
1       8213
Name: count, dtype: int64